# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_snow_shop"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_snow"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


# ---------------------------------------------------
# Models: Medallion Architecture
# ---------------------------------------------------
models:
  dbt_snow_shop:
  
    dbt_snow_shop:
      bronze:
        +materialized: table
        +schema: bronze
      silver:
        +materialized: incremental
        +incremental_strategy: merge
        +schema: silver
        +on_schema_change: sync_all_columns
      gold:
        +materialized: table
        +schema: gold

    dbt_shop_store_2:
      bronze:
        +materialized: table
        +schema: bronze
      silver:
        +materialized: incremental
        +incremental_strategy: merge
        +schema: silver
        +on_schema_change: sync_all_columns
      gold:
        +materialized: table
        +schema: gold
        
  snowflake_spend:
    +enabled: "{{ target.name != 'dev' }}"
